/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "晓锋空间",
  "description": "记录与分享",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/images/favicon.ico"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/images/photo.jpg"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/images/photo.jpg"
      }
    ],
    [
      "meta",
      {
        "http-quiv": "pragma",
        "cotent": "no-cache"
      }
    ],
    [
      "meta",
      {
        "http-quiv": "pragma",
        "cotent": "no-cache,must-revalidate"
      }
    ],
    [
      "meta",
      {
        "http-quiv": "expires",
        "cotent": "0"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/photo.jpg",
        "features": [
          {
            "title": "技术栈",
            "details": "晓锋主要技术栈为vue2,正在努力学习vue3，尚未阅读过vue源码，会尝试自己解读源码，理解其编程思想与方法。常用UI组件库为elementUI,并以此为出发点学习包括elementPlus、ant-design等组件库，并以所学，尝试在此建立自己常用组件库"
          },
          {
            "title": "定义",
            "details": "个人觉得，一个能成长，不给自己设限的人，才能在其道路上愈走愈远，总结与沉淀过去，立足与专注现在，才有资格展望与期待未来。投身于it行业，不仅仅需要过硬的技术支持，在与pm、后端、客户、架构沟通，理解需求，分配时间，分析自身技术去满足业务需求的过程同样重要，而不是一味埋头敲代码，才能成长，才能成为行业'前端'。所以不必把自己局限在前端，或许你才是天生的领导者呢~"
          },
          {
            "title": "方向",
            "details": "在前端领域有所领悟，未来会学习小程序，并以此为基础学习产品相关知识领域，并逐渐向业务方面，即产品经理方面过渡，当然，前端架构师更是长远目标，每个it从业者都会为自己完成的作品感到骄傲！"
          }
        ],
        "footer": "李晓锋 | 一个想被富婆包养的练块程序员"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-994eef30",
      "path": "/",
      "lastUpdated": "6 hours ago",
      "lastUpdatedTimestamp": 1656752332000
    },
    {
      "title": "面试题库",
      "frontmatter": {},
      "regularPath": "/algorithm/",
      "relativePath": "algorithm/README.md",
      "key": "v-12b1b555",
      "path": "/algorithm/",
      "headers": [
        {
          "level": 2,
          "title": "js题库",
          "slug": "js题库"
        },
        {
          "level": 2,
          "title": "vue2题库",
          "slug": "vue2题库"
        },
        {
          "level": 2,
          "title": "vue3题库",
          "slug": "vue3题库"
        },
        {
          "level": 2,
          "title": "小程序题库",
          "slug": "小程序题库"
        },
        {
          "level": 2,
          "title": "业务需求理解",
          "slug": "业务需求理解"
        },
        {
          "level": 2,
          "title": "前端常用优化",
          "slug": "前端常用优化"
        }
      ],
      "lastUpdated": "6 hours ago",
      "lastUpdatedTimestamp": 1656752332000
    },
    {
      "title": "前端积累",
      "frontmatter": {},
      "regularPath": "/accumulate/",
      "relativePath": "accumulate/README.md",
      "key": "v-7107e1ea",
      "path": "/accumulate/",
      "headers": [
        {
          "level": 2,
          "title": "html",
          "slug": "html"
        },
        {
          "level": 2,
          "title": "js",
          "slug": "js"
        },
        {
          "level": 2,
          "title": "css",
          "slug": "css"
        },
        {
          "level": 2,
          "title": "嗷嗷嗷",
          "slug": "嗷嗷嗷"
        }
      ],
      "lastUpdated": "6 hours ago",
      "lastUpdatedTimestamp": 1656752332000
    },
    {
      "title": "手把手教你使用 VuePress 搭建个人博客",
      "frontmatter": {
        "title": "手把手教你使用 VuePress 搭建个人博客",
        "sidebar": "auto",
        "sidebarDepth": 2
      },
      "regularPath": "/guide.html",
      "relativePath": "guide.md",
      "key": "v-3bb1a233",
      "path": "/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "一、为什么你需要一个博客？",
          "slug": "一、为什么你需要一个博客"
        },
        {
          "level": 2,
          "title": "二、什么是 VuePress，为什么要使用 VuePress ？",
          "slug": "二、什么是-vuepress-为什么要使用-vuepress"
        },
        {
          "level": 2,
          "title": "三、开始搭建",
          "slug": "三、开始搭建"
        },
        {
          "level": 3,
          "title": "创建项目文件夹",
          "slug": "创建项目文件夹"
        },
        {
          "level": 3,
          "title": "全局安装 VuePress",
          "slug": "全局安装-vuepress"
        },
        {
          "level": 3,
          "title": "进入 vuepressBlogDemo 文件夹，初始化项目",
          "slug": "进入-vuepressblogdemo-文件夹-初始化项目"
        },
        {
          "level": 3,
          "title": "创建文件夹和文件",
          "slug": "创建文件夹和文件"
        },
        {
          "level": 3,
          "title": "在 config.js 文件中配置网站标题、描述、主题等信息",
          "slug": "在-config-js-文件中配置网站标题、描述、主题等信息"
        },
        {
          "level": 3,
          "title": "在 package.json 文件里添加两个启动命令",
          "slug": "在-package-json-文件里添加两个启动命令"
        },
        {
          "level": 3,
          "title": "一切就绪 🎉 跑起来看看吧",
          "slug": "一切就绪-跑起来看看吧"
        },
        {
          "level": 2,
          "title": "四、一些小亮点",
          "slug": "四、一些小亮点"
        },
        {
          "level": 3,
          "title": "代码块高亮",
          "slug": "代码块高亮"
        },
        {
          "level": 3,
          "title": "自定义容器",
          "slug": "自定义容器"
        },
        {
          "level": 3,
          "title": "支持 Emoji",
          "slug": "支持-emoji"
        },
        {
          "level": 3,
          "title": "支持 PWA",
          "slug": "支持-pwa"
        },
        {
          "level": 2,
          "title": "五、部署上线",
          "slug": "五、部署上线"
        },
        {
          "level": 3,
          "title": "登陆 Github",
          "slug": "登陆-github"
        },
        {
          "level": 3,
          "title": "新建仓库一： USERNAME.github.io （不用克隆到本地）",
          "slug": "新建仓库一-username-github-io-不用克隆到本地"
        },
        {
          "level": 3,
          "title": "新建仓库二：随便起一个名字，比如：vuepressBlog （克隆到本地）",
          "slug": "新建仓库二-随便起一个名字-比如-vuepressblog-克隆到本地"
        },
        {
          "level": 3,
          "title": "修改仓库二中的 deploy.sh 发布脚本",
          "slug": "修改仓库二中的-deploy-sh-发布脚本"
        },
        {
          "level": 3,
          "title": "在 package.json 文件夹中添加发布命令（使用工具包的请忽略）",
          "slug": "在-package-json-文件夹中添加发布命令-使用工具包的请忽略"
        },
        {
          "level": 3,
          "title": "👏 大功告成，运行发布命令",
          "slug": "大功告成-运行发布命令"
        },
        {
          "level": 2,
          "title": "六、发布到自己的个人域名",
          "slug": "六、发布到自己的个人域名"
        },
        {
          "level": 3,
          "title": "购买域名",
          "slug": "购买域名"
        },
        {
          "level": 3,
          "title": "修改仓库二中的 deploy.sh 文件",
          "slug": "修改仓库二中的-deploy-sh-文件"
        },
        {
          "level": 3,
          "title": "👏 大功告成，打开 https://www.zhangyunchen.cc 看一下吧~~~",
          "slug": "大功告成-打开-https-www-zhangyunchen-cc-看一下吧"
        },
        {
          "level": 2,
          "title": "七、最后",
          "slug": "七、最后"
        }
      ],
      "lastUpdated": "6 hours ago",
      "lastUpdatedTimestamp": 1656752332000
    },
    {
      "title": "你",
      "frontmatter": {},
      "regularPath": "/others/",
      "relativePath": "others/README.md",
      "key": "v-3e9d102a",
      "path": "/others/",
      "lastUpdated": "6 hours ago",
      "lastUpdatedTimestamp": 1656752332000
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "前端基础",
        "link": "/accumulate/"
      },
      {
        "text": "面试题库",
        "link": "/algorithm/"
      },
      {
        "text": "诗和远方",
        "link": "/others/"
      },
      {
        "text": "联系晓锋",
        "link": "https://github.com/lianzefeng2021"
      }
    ],
    "sidebar": "auto",
    "sidebarDepth": 2
  }
}